/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bigwanggang;

import java.awt.Color;
import java.net.InetAddress;
import java.net.UnknownHostException;

/**
 *
 * @author ADMIN
 */
public class MainInterface extends javax.swing.JFrame {

    private ShotPlaneDisplayConponent gameDisplayComponent;
    private Plane plane = new Plane(6, 5, 6, 8);
    private boolean serverIsOn = false;
    
    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
        InetAddress localhostAddress = null;
        try {
            localhostAddress = InetAddress.getLocalHost();
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }
        if (localhostAddress != null) {
            ipField.setText(localhostAddress.getHostAddress());
        }
        gameDisplayComponent = new ShotPlaneDisplayConponent(plane);
        singleInterface.add(gameDisplayComponent);
        playMainInterface.setVisible(false);
//        singleInterface.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        version = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        menuBar = new javax.swing.JPanel();
        lblPlay = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        lblRecord = new javax.swing.JLabel();
        lblUserInfo = new javax.swing.JLabel();
        lblAboutUs = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        singleInterface = new javax.swing.JPanel();
        welcome = new javax.swing.JTextField();
        btnUp = new javax.swing.JButton();
        btnLeft = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        chatInputWindow = new javax.swing.JScrollPane();
        chatInputArea = new javax.swing.JTextArea();
        btnUp5 = new javax.swing.JButton();
        btnUp6 = new javax.swing.JButton();
        chatDisplayWindow = new javax.swing.JScrollPane();
        chatDisplayArea = new javax.swing.JTextArea();
        lblChatInputArea = new javax.swing.JLabel();
        lblChatDisplayArea = new javax.swing.JLabel();
        ipField = new javax.swing.JTextField();
        lblIpField = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        portField = new javax.swing.JTextField();
        connectionButton = new javax.swing.JButton();
        playMainInterface = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        lblSelectMode = new javax.swing.JLabel();
        btnMultiplayer = new javax.swing.JButton();
        btnSingle = new javax.swing.JButton();
        lblCopyRight = new java.awt.Label();
        lblHelp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMART GAME by tuhalang ft nhanbka");
        setMaximumSize(new java.awt.Dimension(780, 425));
        setMinimumSize(new java.awt.Dimension(780, 425));
        setPreferredSize(new java.awt.Dimension(780, 425));
        setResizable(false);

        version.setFont(new java.awt.Font("Calibri", 3, 12)); // NOI18N
        version.setText("VERSION 1.0");

        menuBar.setBackground(new java.awt.Color(203, 234, 245));
        menuBar.setMaximumSize(new java.awt.Dimension(98, 393));
        menuBar.setMinimumSize(new java.awt.Dimension(98, 393));

        lblPlay.setBackground(new java.awt.Color(132, 206, 232));
        lblPlay.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        lblPlay.setText("Play");
        lblPlay.setAlignmentX(1.0F);
        lblPlay.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lblPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lblPlay.setOpaque(true);

        lblDashboard.setBackground(new java.awt.Color(203, 234, 245));
        lblDashboard.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        lblDashboard.setText("Dashboard");
        lblDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblDashboard.setOpaque(true);

        lblRecord.setBackground(new java.awt.Color(203, 234, 245));
        lblRecord.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/record.png"))); // NOI18N
        lblRecord.setText("Record");
        lblRecord.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lblRecord.setOpaque(true);

        lblUserInfo.setBackground(new java.awt.Color(203, 234, 245));
        lblUserInfo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblUserInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        lblUserInfo.setText("User Info");
        lblUserInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lblUserInfo.setOpaque(true);

        lblAboutUs.setBackground(new java.awt.Color(203, 234, 245));
        lblAboutUs.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about_us.png"))); // NOI18N
        lblAboutUs.setText("About Us");
        lblAboutUs.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lblAboutUs.setOpaque(true);

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
            .addComponent(lblPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblAboutUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addComponent(lblPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 143, Short.MAX_VALUE))
        );

        jLayeredPane1.setBackground(new java.awt.Color(132, 206, 232));
        jLayeredPane1.setOpaque(true);

        singleInterface.setBackground(new java.awt.Color(132, 206, 232));
        singleInterface.setMaximumSize(new java.awt.Dimension(684, 394));
        singleInterface.setMinimumSize(new java.awt.Dimension(684, 394));

        welcome.setEditable(false);
        welcome.setBackground(new java.awt.Color(132, 206, 232));
        welcome.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        welcome.setText("Hello");
        welcome.setBorder(null);

        btnUp.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_arrow-up.png"))); // NOI18N
        btnUp.setText("Up");

        btnLeft.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_arrow-left.png"))); // NOI18N

        btnDown.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_arrow-down.png"))); // NOI18N
        btnDown.setText("Down");

        btnRight.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconfinder_arrow-right.png"))); // NOI18N

        btnOK.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnOK.setText("OK");
        btnOK.setMaximumSize(new java.awt.Dimension(224, 25));
        btnOK.setMinimumSize(new java.awt.Dimension(224, 25));
        btnOK.setPreferredSize(new java.awt.Dimension(224, 25));

        btnSend.setText("SEND");

        chatInputArea.setColumns(20);
        chatInputArea.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        chatInputArea.setLineWrap(true);
        chatInputArea.setRows(5);
        chatInputWindow.setViewportView(chatInputArea);

        btnUp5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnUp5.setText("<<");

        btnUp6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnUp6.setText(">>");

        chatDisplayArea.setColumns(20);
        chatDisplayArea.setRows(5);
        chatDisplayWindow.setViewportView(chatDisplayArea);

        lblChatInputArea.setLabelFor(chatInputArea);
        lblChatInputArea.setText("Your Message");

        lblChatDisplayArea.setLabelFor(chatDisplayArea);
        lblChatDisplayArea.setText("Your dialouge");

        ipField.setEditable(false);
        ipField.setEnabled(false);

        lblIpField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblIpField.setLabelFor(ipField);
        lblIpField.setText("IP:");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel1.setText("Port:");

        connectionButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        connectionButton.setText("Connect");
        connectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout singleInterfaceLayout = new javax.swing.GroupLayout(singleInterface);
        singleInterface.setLayout(singleInterfaceLayout);
        singleInterfaceLayout.setHorizontalGroup(
            singleInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(singleInterfaceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(singleInterfaceLayout.createSequentialGroup()
                .addGroup(singleInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(singleInterfaceLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblIpField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ipField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(singleInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(singleInterfaceLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(connectionButton)
                                .addGap(26, 26, 26)
                                .addGroup(singleInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(singleInterfaceLayout.createSequentialGroup()
                                        .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(singleInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnUp6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(singleInterfaceLayout.createSequentialGroup()
                                                .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, singleInterfaceLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(singleInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(singleInterfaceLayout.createSequentialGroup()
                                        .addComponent(btnUp5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(chatInputWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSend))))
                    .addGroup(singleInterfaceLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(singleInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChatDisplayArea)
                            .addComponent(chatDisplayWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChatInputArea))))
                .addGap(32, 32, 32))
        );
        singleInterfaceLayout.setVerticalGroup(
            singleInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, singleInterfaceLayout.createSequentialGroup()
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblChatDisplayArea)
                .addGap(0, 0, 0)
                .addComponent(chatDisplayWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblChatInputArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(singleInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chatInputWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(singleInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUp6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUp5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(singleInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRight, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(singleInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIpField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        playMainInterface.setBackground(new java.awt.Color(132, 206, 232));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(132, 206, 232));
        jTextField1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextField1.setText("Hello");
        jTextField1.setBorder(null);

        lblSelectMode.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        lblSelectMode.setText("Select Mode");

        btnMultiplayer.setBackground(new java.awt.Color(253, 233, 250));
        btnMultiplayer.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btnMultiplayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/multiplayer.png"))); // NOI18N
        btnMultiplayer.setText("Multiplayer");
        btnMultiplayer.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1)));
        btnMultiplayer.setBorderPainted(false);
        btnMultiplayer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMultiplayer.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnMultiplayer.setName("btnMultiplayer"); // NOI18N

        btnSingle.setBackground(new java.awt.Color(253, 233, 250));
        btnSingle.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btnSingle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/single_player.png"))); // NOI18N
        btnSingle.setText("Single");
        btnSingle.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1)));
        btnSingle.setBorderPainted(false);
        btnSingle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSingle.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnSingle.setName("btnSingle"); // NOI18N

        lblCopyRight.setAlignment(java.awt.Label.CENTER);
        lblCopyRight.setEnabled(false);
        lblCopyRight.setMaximumSize(new java.awt.Dimension(220, 20));
        lblCopyRight.setText("Copyrights 2020 @ All Rights Reserved");

        lblHelp.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        lblHelp.setForeground(new java.awt.Color(241, 53, 0));
        lblHelp.setText("Need Help?");

        javax.swing.GroupLayout playMainInterfaceLayout = new javax.swing.GroupLayout(playMainInterface);
        playMainInterface.setLayout(playMainInterfaceLayout);
        playMainInterfaceLayout.setHorizontalGroup(
            playMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playMainInterfaceLayout.createSequentialGroup()
                .addGroup(playMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playMainInterfaceLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblCopyRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addComponent(lblHelp))
                    .addGroup(playMainInterfaceLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(playMainInterfaceLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addGroup(playMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSingle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSelectMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMultiplayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        playMainInterfaceLayout.setVerticalGroup(
            playMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playMainInterfaceLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(playMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playMainInterfaceLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblSelectMode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMultiplayer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSingle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(lblCopyRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(playMainInterfaceLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHelp)))
                .addGap(34, 34, 34))
        );

        jLayeredPane1.setLayer(singleInterface, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(playMainInterface, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(singleInterface, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(playMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(singleInterface, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectionButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_connectionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnMultiplayer;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnRight;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSingle;
    private javax.swing.JButton btnUp;
    private javax.swing.JButton btnUp5;
    private javax.swing.JButton btnUp6;
    private javax.swing.JTextArea chatDisplayArea;
    private javax.swing.JScrollPane chatDisplayWindow;
    private javax.swing.JTextArea chatInputArea;
    private javax.swing.JScrollPane chatInputWindow;
    private javax.swing.JButton connectionButton;
    private javax.swing.JTextField ipField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAboutUs;
    private javax.swing.JLabel lblChatDisplayArea;
    private javax.swing.JLabel lblChatInputArea;
    private java.awt.Label lblCopyRight;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblIpField;
    private javax.swing.JLabel lblPlay;
    private javax.swing.JLabel lblRecord;
    private javax.swing.JLabel lblSelectMode;
    private javax.swing.JLabel lblUserInfo;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel playMainInterface;
    private javax.swing.JTextField portField;
    private javax.swing.JPanel singleInterface;
    private java.awt.Label version;
    private javax.swing.JTextField welcome;
    // End of variables declaration//GEN-END:variables
}
