/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client.gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Rectangle2D;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.regex.Matcher;

/**
 *
 * @author ADMIN
 */
public class AboutUsTab extends javax.swing.JFrame {

    private ShotPlaneDisplayConponent gameDisplayComponent;
    private Plane plane = new Plane(6, 5, 6, 8);
    private PrintWriter pw;                                     // for Chat
    private boolean serverIsReady = false;
    
    /**
     * Creates new form MainInterface
     */
    public AboutUsTab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        version = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        menuBar = new javax.swing.JPanel();
        lblPlay = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        lblRecord = new javax.swing.JLabel();
        lblUserInfo = new javax.swing.JLabel();
        lblAboutUs = new javax.swing.JLabel();
        UserInfoMainPanel = new javax.swing.JLayeredPane();
        playMainInterface = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        lblCopyRight = new java.awt.Label();
        lblHelp = new javax.swing.JLabel();
        content = new javax.swing.JSplitPane();
        NhanLT = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HungPV = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMART GAME by tuhalang ft nhanbka");
        setBackground(new java.awt.Color(203, 234, 245));
        setMinimumSize(new java.awt.Dimension(782, 424));
        setResizable(false);

        version.setFont(new java.awt.Font("Calibri", 3, 12)); // NOI18N
        version.setText("VERSION 1.0");

        menuBar.setBackground(new java.awt.Color(203, 234, 245));
        menuBar.setMaximumSize(new java.awt.Dimension(98, 394));
        menuBar.setMinimumSize(new java.awt.Dimension(98, 394));
        menuBar.setPreferredSize(new java.awt.Dimension(98, 394));

        lblPlay.setBackground(new java.awt.Color(203, 234, 245));
        lblPlay.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/play.png"))); // NOI18N
        lblPlay.setText("Play");
        lblPlay.setAlignmentX(1.0F);
        lblPlay.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lblPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lblPlay.setOpaque(true);

        lblDashboard.setBackground(new java.awt.Color(203, 234, 245));
        lblDashboard.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N
        lblDashboard.setText("Dashboard");
        lblDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblDashboard.setOpaque(true);

        lblRecord.setBackground(new java.awt.Color(203, 234, 245));
        lblRecord.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/record.png"))); // NOI18N
        lblRecord.setText("Record");
        lblRecord.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lblRecord.setOpaque(true);

        lblUserInfo.setBackground(new java.awt.Color(203, 234, 245));
        lblUserInfo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblUserInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        lblUserInfo.setText("User Info");
        lblUserInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lblUserInfo.setOpaque(true);

        lblAboutUs.setBackground(new java.awt.Color(132, 206, 232));
        lblAboutUs.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about_us.png"))); // NOI18N
        lblAboutUs.setText("About Us");
        lblAboutUs.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        lblAboutUs.setOpaque(true);

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 98, Short.MAX_VALUE)
            .addComponent(lblPlay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblAboutUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addComponent(lblPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblAboutUs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        UserInfoMainPanel.setBackground(new java.awt.Color(132, 206, 232));
        UserInfoMainPanel.setOpaque(true);

        playMainInterface.setBackground(new java.awt.Color(132, 206, 232));
        playMainInterface.setMaximumSize(new java.awt.Dimension(684, 394));
        playMainInterface.setMinimumSize(new java.awt.Dimension(684, 394));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(132, 206, 232));
        jTextField1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTextField1.setText("Hello");
        jTextField1.setBorder(null);

        lblCopyRight.setAlignment(java.awt.Label.CENTER);
        lblCopyRight.setEnabled(false);
        lblCopyRight.setMaximumSize(new java.awt.Dimension(220, 20));
        lblCopyRight.setText("Copyrights 2020 @ All Rights Reserved");

        lblHelp.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        lblHelp.setForeground(new java.awt.Color(241, 53, 0));
        lblHelp.setText("Need Help?");

        content.setBackground(new java.awt.Color(132, 206, 232));
        content.setDividerLocation(300);
        content.setMaximumSize(new java.awt.Dimension(600, 300));
        content.setMinimumSize(new java.awt.Dimension(600, 300));

        NhanLT.setBackground(new java.awt.Color(132, 206, 232));
        NhanLT.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setText("Lê Trọng Nhân");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nhanlt.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("KTMT.06 K62");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setText("20173292");

        javax.swing.GroupLayout NhanLTLayout = new javax.swing.GroupLayout(NhanLT);
        NhanLT.setLayout(NhanLTLayout);
        NhanLTLayout.setHorizontalGroup(
            NhanLTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanLTLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NhanLTLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(NhanLTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(NhanLTLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(jLabel3))
                .addGap(45, 45, 45))
        );
        NhanLTLayout.setVerticalGroup(
            NhanLTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhanLTLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NhanLTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34))
        );

        content.setLeftComponent(NhanLT);

        HungPV.setBackground(new java.awt.Color(132, 206, 232));
        HungPV.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setText("Phạm Văn Hùng");

        javax.swing.GroupLayout HungPVLayout = new javax.swing.GroupLayout(HungPV);
        HungPV.setLayout(HungPVLayout);
        HungPVLayout.setHorizontalGroup(
            HungPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HungPVLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 131, Short.MAX_VALUE))
        );
        HungPVLayout.setVerticalGroup(
            HungPVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HungPVLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 279, Short.MAX_VALUE))
        );

        content.setRightComponent(HungPV);

        javax.swing.GroupLayout playMainInterfaceLayout = new javax.swing.GroupLayout(playMainInterface);
        playMainInterface.setLayout(playMainInterfaceLayout);
        playMainInterfaceLayout.setHorizontalGroup(
            playMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playMainInterfaceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(playMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playMainInterfaceLayout.createSequentialGroup()
                        .addComponent(lblCopyRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addComponent(lblHelp))
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playMainInterfaceLayout.createSequentialGroup()
                .addGap(0, 34, Short.MAX_VALUE)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        playMainInterfaceLayout.setVerticalGroup(
            playMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playMainInterfaceLayout.createSequentialGroup()
                .addGroup(playMainInterfaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(playMainInterfaceLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblCopyRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(playMainInterfaceLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(lblHelp)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        UserInfoMainPanel.setLayer(playMainInterface, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout UserInfoMainPanelLayout = new javax.swing.GroupLayout(UserInfoMainPanel);
        UserInfoMainPanel.setLayout(UserInfoMainPanelLayout);
        UserInfoMainPanelLayout.setHorizontalGroup(
            UserInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        UserInfoMainPanelLayout.setVerticalGroup(
            UserInfoMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playMainInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(UserInfoMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UserInfoMainPanel)
                        .addGap(0, 0, 0))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayTab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayTab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HungPV;
    private javax.swing.JPanel NhanLT;
    private javax.swing.JLayeredPane UserInfoMainPanel;
    private javax.swing.JSplitPane content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAboutUs;
    private java.awt.Label lblCopyRight;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblPlay;
    private javax.swing.JLabel lblRecord;
    private javax.swing.JLabel lblUserInfo;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel playMainInterface;
    private java.awt.Label version;
    // End of variables declaration//GEN-END:variables

    /*
     *
     *      Declare nested class to handle event
     *
     *
    */
    private class ButtonAction implements ActionListener {
        public void actionPerformed(ActionEvent event) {
            String input = event.getActionCommand();
        }
    }
    
}
